### ISSUE TITLE
No Data when building apk

### ISSUE THREAD

**Issue by movieator** [Kirk-Patrick/flutter_wifi_info_plugin#2]
Hi, when i use the plugin on "flutter run", it works properly and i get the mac address from the device as i want. When i build the apk and start the app, the mac address of the same device as before, is empty.
Is there any problem with the plugin or i' m doing something wrong?

The output of "flutter doctor" is:

> [√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale el-GR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.42.1)
[√] Connected device (1 available)

**Comment by Tsagaanbayr1** [comment]
Add the method to the **WifiInfoPlugin** class 

```
  static Future<String> get macAdress async {
    return await _channel.invokeMethod('getWifiDetails');
  }
```
Please this method on your project instead.
```
Future<String> getMacAddress() async {
  WifiInfoWrapper wifiObject;
  String macAddress;
  try {
    macAddress = (await WifiInfoPlugin.wifiDetails).macAddress;
  } catch (_) {
    macAddress = await WifiInfoPlugin.wifiDetailsByString;
  }
  return macAddress;
}
```

hope it's helpful

**Comment by Kirk-Patrick** [comment]
This issue will be updated in the next release
