### ISSUE TITLE
Please upgrade to null safety!

### ISSUE THREAD

**Issue by yurtemre7** [Kirk-Patrick/flutter_wifi_info_plugin#5]
It would help me so much! In case you need help with the migration, just write me on telegram: [emredev](https://t.me/emredev)

**Comment by brasizza** [comment]
I have a branch with null safety @yurtemre7 , its in pull request. but if you want just look at my git and get my repository full null safety and upgraded to v2 plugin as well. #10

**Comment by EgHubs** [comment]
Will I found [this](https://pub.dev/packages/network_info_plus) package which is supported by the flutter community

**Comment by Kirk-Patrick** [comment]
Null safety checks where merged.
