### ISSUE TITLE
能否获取当前连接的设备数量

### ISSUE THREAD

**Issue by mengsiyitiaojie** [Kirk-Patrick/flutter_wifi_info_plugin#6]
能否获取当前wifi连接的设备数量

**Comment by 0xdecade** [comment]
If your question is still actual, then I already did that with the [WiFi Hunter](https://pub.dev/packages/wifi_hunter) . It was based on this plugin but it's _deprecated_ now.

Just add library into pubspec.yaml, run ``` flutter pub get ```, import library and do something like this: 

```dart
int getNeighboursCount() async {
  final _wifiObject = await scanWiFi();
  return _wifiObject.ssids.length;
}
```

Be careful: the code above hasn't been running, so it can contain mistakes.

**Comment by Kirk-Patrick** [comment]
closing
